### ISSUE TITLE
Build stuck with Build version message

### ISSUE THREAD

**Issue by gaelfortin** [theAkito/docker-icedrive#1]
#### Required Information
Project version
9016c97@master

Distro version
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Kernel version
Linux gaelf 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Steps to reproduce
Hello, I am trying to install docker-icedrive for the first time.  
I get the error when building with `bash docker-build.sh`.

#### Expected behaviour
Building should occur.

#### Actual behaviour
I get the following message:
```
Build version:
==> Presumably Docker tag version.
```
This message stays forever.

Thanks for your help!

**Comment by theAkito** [comment]
Thank you for pointing out, that my default build script is unintuitive. I will see how I can improve that. 🙂 

To future readers:

The script is interactive by default and expects answers from the builder.

https://github.com/theAkito/docker-icedrive/blob/9016c97d6513c80f1eae54d56d8107da76fbe6fc/docker-build.sh#L70

However, the script can also be automatised.

https://github.com/theAkito/docker-icedrive/blob/9016c97d6513c80f1eae54d56d8107da76fbe6fc/docker-build.sh#L55-L68

**Comment by gaelfortin** [comment]
Thanks for your answer. Indeed I understood that the script was awaiting package version when reading your detailed script.
